# Generated by Django 5.2.14 on 2026-05-31 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('PROFILE_UPDATE', 'Profile update'), ('ITEM_CREATE', 'Item created'), ('ITEM_UPDATE', 'Item updated'), ('ITEM_DELETE', 'Item deleted'), ('ACCESS_DENIED', 'Access denied')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
